# fly.toml app configuration file generated for jhs512-glog-1 on 2025-03-11T14:09:10+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jhs512-glog-1'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
source = "jhs512_glog_1__gen" # 볼륨 이름
destination = "/gen" # 도커 컨테이너 내부에 마운트할 경로